github: [metadata]
theme: jekyll-theme-hacker
title: MPS Robotics
description: Information about robotics at Mason Public Schools in Mason, MI, including FIRST LEGO League
# google_analytics: [Your Google Analytics tracking ID]
navigation:
 - title: Home
   url: /index.html
 - title: Resources
   url: /resources.html
 - title: Blog
   url: /posts.html
# Disqus Comments
disqus:
  shortname: mpsrobotics
